[package]
name = "CloudToolsLib"
version = "0.3.2"
authors = ["Chris https://github.com/electronicsleep"]
edition = "2024"

[lib]
name = "cloudtools"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"

[dependencies.pyo3]
version = "0.26.0"
features = ["extension-module"]
